services:
  postgres:
    image: postgres:15-alpine
    container_name: movie_db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie_db
    ports:
      - "5432:5432"
    volumes:
      - movie_postgres_data:/var/lib/postgresql/data
    networks:
      - movie_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: movie_db_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - movie_network

  app:
    build: .
    container_name: movie_db_api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: movie_db
      DB_PORT: "5432"
      PORT: "8080"
    networks:
      - movie_network

volumes:
  movie_postgres_data:

networks:
  movie_network:
    driver: bridge